### ISSUE TITLE
Do fizzbuzz.py

### ISSUE THREAD

**Issue by Soy-Bin** [practice-githubflow-8/fizzbuzz#1]
## Description

fizzbuzz 기능 구현

 1부터 n까지의 숫자를 받아서
 3의 배수면 fizz
 5의 배수면 buzz
 15의 배수면 fizzbuzz를 출력한다.

## Tasks
- [x] 3의 배수면 fizz 출력
- [x] 5의 배수면 fizz 출력
- [x]  15의 배수면 fizz 출력
